# Generated by Django 4.1 on 2024-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20240409_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
