# Generated by Django 3.0 on 2024-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_notification', '0003_alter_notification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]