# Generated by Django 4.1 on 2024-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_notification', '0004_auto_20240409_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
